services:
  backend1:
    restart: always
    build:
      context: ../backend
    expose:
      - 8000
    environment:
      - SERVICE_NAME=backend1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_HOST=${DATABASE_IP}
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      lb_net:
        ipv4_address: ${BACKEND_IP_1}

  backend2:
    restart: always
    build:
      context: ../backend
    expose:
      - 8000
    environment:
      - SERVICE_NAME=backend2
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_HOST=${DATABASE_IP}
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      lb_net:
        ipv4_address: ${BACKEND_IP_2}

  calendar_api:
    restart: always
    build:
      context: ../calendar-api
    expose:
      - 8000
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_HOST=${DATABASE_IP}
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      lb_net:
        ipv4_address: ${CALENDAR_API_IP}
  
  calendar_mcp:
    restart: always
    build:
      context: ../calendar-mcp
    expose:
      - 8040
    environment:
      - PORT=8040
      - CALENDAR_API_BASE_URL=${CALENDAR_API_IP}
    depends_on:
      - db
    networks:
      lb_net:
        ipv4_address: ${CALENDAR_MCP_IP}

  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - lb_net
  
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      lb_net:
        ipv4_address: ${DATABASE_IP}

volumes:
  postgres_data:

networks:
  lb_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24